apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- gotk-components.yaml
- gotk-sync.yaml
images:
  - name: ghcr.io/fluxcd/kustomize-controller
    newName: acrakslsuoccqde6qa2.azurecr.io/fluxcd/kustomize-controller
  - name: ghcr.io/fluxcd/source-controller
    newName: acrakslsuoccqde6qa2.azurecr.io/fluxcd/source-controller
